### PR TITLE
update to new sentry api

### PR DESCRIPTION
**Pull request by Julian-B90**

### CODE REVIEW

**Comment by Julian-B90** [comment]
@niksamokhvalov in travis the `$GITHUB_AUTH_TOKEN  is not defined.`

**Comment by Julian-B90** [comment]
Her are my Travis Tests https://travis-ci.org/Julian-B90/yii2-sentry/builds/560462452?utm_source=github_status&utm_medium=notification

**Comment by Julian-B90** [comment]
@niksamokhvalov kann you review this MR?

**Comment by niksamokhvalov** [comment]
Thanks for PR and waiting!

**Pull request merged**
